config/routes.rb
Rails.application.routes.draw do
 get '/hello', to: 'students#hello', as: 'hello'

#  post '/students', to: 'students#create'
 resources :students,except: [:destroy, :edit, :update]
# get '/students', to: 'students#index', as: 'students'

# post '/students', to: 'students#create'

# get '/students/new',  to: 'students#new', as: 'new_student'

# get '/students/:id/edit', to: 'students#edit', as: 'edit_student'

# get '/students/:id', to: 'students#show', as: 'student'

# patch '/students/:id', to: 'students#update'
# put '/students/:id', to: 'students#update'

# delete '/students/:id', to: 'students#destroy'
 root 'students#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/student.rb
class Student < ApplicationRecord
  validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
    @students = Student.all
    @jackie = Student.find_by_name('Jackie')
    @parameters = params
  end

  def show
    @student = Student.find(params[:id])
  end

  def new
    @student = Student.new
  end

  def create
    @student = Student.create(name: params[:student][:name], email: params[:student][:email])
  end

  def hello

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CoderAcademy</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav><h1><%= link_to 'Hello', hello_path%> | <%= link_to 'Students', students_path %></h1></nav>
    <%= yield %>
  </body>
</html>

app/views/students/hello.html.erb
<h1>HELLO</h1>

app/views/students/index.html.erb
<h1>Coder Students</h1>

<% @students.each do |student| %>
  <h2>Name: <%= student.name %><%= link_to 'Show', student%></h2>
<% end %>

<h5> <%= @jackie.email %> </h5>

<p><%= link_to('Create New Student', new_student_path)%></p>

app/views/students/new.html.erb
<%= form_with model: @student do |form|%>
  <%= form.label(:name) %>
  <%= form.text_field :name%>

  <%= form.label :email %>
  <%= form.text_field :email%>
  
  <%= form.submit 'MAKE THIS STUDENT!!!' %>
<% end %>

app/views/students/show.html.erb
<div class="title">
<h1><%= @student.email%></h1>
</div>